### ISSUE TITLE
fanpaket down

### ISSUE THREAD

**Issue by Codingboy** [flyx/DSA-4.1-Heldendokument#1]
Das Fanpaket ist nicht mehr unter http://www.ulisses-spiele.de/download/889/ zu erreichen...

**Comment by flyx** [comment]
Das war abzusehen. Die Lizenz gibt mir leider keine Möglichkeit, das hier selbst zu hosten, daher ist das wohl leider ein CANTFIX :/

**Comment by Codingboy** [comment]
;'(
Ulisses kommt mir in der Hinsicht ziemlich communityfeindlich vor.
Ist jetzt heute schon das 2. Tool, das ich sehe, das wegen nicht mehr verfügbaren Downloads nicht mehr funktioniert.
Habe mal bei denen angefragt...

**Comment by flyx** [comment]
Der Charakterbogen benutzt allerdings das Fanpaket gar nicht. Er braucht nur das Handout vom WdS, das weiterhin [hier](https://ulisses-spiele.de/assets/document/0A/Wege-des-Schwerts_Handouts_fee3.pdf) verfügbar ist – daraus wird der Hintergrund extrahiert.

Was nicht funktioniert, sind die Funktionen für Seitenrahmen und Zettelhintergründe, die von der DSA-LaTeX-Klasse bereitgestellt werden. Aber die verwendet das Heldendokument nicht. Insofern ist das hier vielleicht doch kein CANTFIX. Kannst du beschreiben, wo du bei der Erstellung in einen Fehler läufst?

**Comment by flyx** [comment]
Fanpaket ist wohl wieder da unter der URL.
