### ISSUE TITLE
Typo Astrale Regeneration

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#10]
Ist der letzte Bug-Report für heute 😉 sehr cooler Generator, hab einfach mal die ganze Gruppe durch gejagt um Edge-Cases zu finden. Könnte mir gut vorstellen, dass wir auf deinen Bogen wechseln.

Anbei ein .patch file für einen Typo: [typo.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8839826/typo.zip)

**Comment by flyx** [comment]
Danke! Es ist sehr hilfreich für die Bugsuche, wenn andere Leute den Generator verwenden :).
