### ISSUE TITLE
Zweihänder wird nicht importiert

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#11]
![grafik](https://user-images.githubusercontent.com/58633378/172118266-e014bce5-cd5b-4226-86ee-79b28637435e.png)

Der ganz normale Zweihänder wird nicht importiert und angezeigt. Hab schon ins heldensoftware-meta.xml geschaut aber mir ist nichts aufgefallen 🤔 

Wie üblich anbei der Held zum reproduzieren: [FirunjaWolpjes.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8842699/FirunjaWolpjes.zip)

**Comment by flyx** [comment]
Ein wunderschöner Bug!

Die Zuordnung zu Talenten war so implementiert, dass nach einem Talent gesucht wurde, dessen Name so *anfängt* wie das in der Waffenliste notierte Talent. Das war deshalb so, weil ich die Spezialisierungen anfangs noch hinten in den Talentnamen geschrieben hab statt in einen eigenen Wert.

Ob ein Talentnamen mit dem gegebenen Namen *anfängt*, wurde geprüft, indem ein Pattern mit `^` + gegebener Name gebildet und darauf gematcht wurde, weil Lua nicht so wahnsinnig viele String-Funktionen hat. Ja, und `-` ist halt ein Sonderzeichen in Patterns, deshalb geht das dann schief, wenn das Talent „Zweihandschwerter/-säbel“ heißt.
