### ISSUE TITLE
Transparenz für Ritualkennntnis und Regeneration

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#12]
Mir ist aufgefallen, dass die beiden Felder bei Verwendung des Hintegrundbildes nicht transparent, sondern weiß rendern:

![grafik](https://user-images.githubusercontent.com/58633378/172118659-4f355aa8-d798-4075-a8da-ef96dc1144d1.png)

**Comment by flyx** [comment]
Ja, das ist so gedacht. Damit wird angezeigt, dass dies Felder sind, deren Werte sich ändern können. Der Neueinsteiger kann so erkennen, dass etwa die Regeneration nicht immer genau so auf dem Bogen steht, sondern die eingetragene Formel sich aus Dingen ableitet und sich ändern kann. Außerdem ist der Heldenbogen ja *auch* dafür ausgelegt, dass man sich ihn blanko drucken und die Werte von Hand ausfüllen kann; an den Stellen mit weißen Kästen wäre sonst nicht offensichtlich, dass man da was eintragen kann.

Das funktioniert natürlich nicht, wenn man den Bogen ohne Hintergrund druckt. Hm. Das Original-Heldendokument hat bei der Ritualkenntnis Rahmen um den Wert, das finde ich unschön; aber ich könnte mir vorstellen, die Ritualkenntnis einfach in Tabellenform zu notieren wie alles andere. Ich werde ein wenig darüber sinnieren.

**Comment by pielmach** [comment]
Sind etwa für das Blanko-Drucken die "Templates"? Ich hatte mich schon gewundert wozu die in der WebUI sind :thinking: 

Das mit dem Neueinsteiger verstehe ich, frage mich aber ob in der Praxis nicht das einheitliche Layout (also ohne weiße Fläche) mehr wiegt. Zumal es dort einen einfach etwas anspringt. Bei der Ritualkenntnis finde ich stört es optisch weniger als bei der Regeneration. Wer einen Magiebegabten spielt, weiss das doch selbst als Neueinsteiger relativ rasch, spätestens nach der Generierung. Aber das ist alles schon Stilkritik auf hohem Niveau :wink:

**Comment by flyx** [comment]
Ja, die Templates sind dafür, und für Leute, die die Heldensoftware gar nicht benutzen. Ich zum Beispiel generiere gerne ohne die Software mit Papier und Bleistift. Nicht weil sie irgendwie schlecht wäre, sondern einfach, weil mir das ein besseres Gefühl für den Charakter gibt.

Wenn ich generiert habe, schreibe ich das Resultat direkt in eine `.lua` Datei und steigere dann später über die Ereignisse des Bogens.

**Comment by flyx** [comment]
Da sind jetzt Striche unter den ausfüllbaren Werten, das funktioniert unabhängig vom Hintergrundbild und ist konform mit anderen Stellen (-> Ausweichen-Formel). Die weißen Boxen sind weg und ich hab das Layout minimal aufgehübscht.
