### ISSUE TITLE
Zauber Ignifaxius schlägt fehlt | Lahm und Astrale Regeneration nicht berücksichtigt

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#4]
1. Der Zauber Ignifaxius erzeugt einen Fehler, vermutlich wegen des Tippfehlers Ingifaxius in der `heldensoftware-meta.xml`. Kann manuell in der lua Datei korrigiert werden, dann läuft es durch.
2. Weiterhin ist mir aufgefallen, dass der Nachteil Lahm nicht korrekt von der GS abgezogen wird, hier steht immer der Starwert auf Seite 1. Im Helden Generator wird der Startwert angezeigt und der aktuelle Wert anhand von BE bestimmt.
3. Der Vorteil Astrale Regeneration scheint bei der Berechnung der Regeneration pro Phase auch ignoriert zu werden.

Anbei ein XML um alle beschriebenen Probleme zu reproduzieren.

[BernholmvonBellentorKampagne.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8791128/BernholmvonBellentorKampagne.zip)

**Comment by flyx** [comment]
Danke für die Fehlerbeschreibung, ist behoben. In Zukunft führen Zauber, deren Namen nicht bekannt ist, auch nicht mehr dazu, dass eine ungültige Datei generiert wird, sondern es fehlen dann nur die entsprechenden Daten (Seitenzahl, Merkmale).
