### ISSUE TITLE
Muttersprache wird nicht korrekt erkannt

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#5]
Bei einem Helden mit Muttersprache Garethi wird diese nicht erkannt. Beim Erstellen des PDF crasht der Generator. XML des Helden im Anhang zur Reproduktion. In der Helden-Software wird Garethi fett markiert als Muttersprache.

[WeldmarSteinhauer.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8839771/WeldmarSteinhauer.zip)

**Comment by pielmach** [comment]
[VitoBalonkaro.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8839799/VitoBalonkaro.zip) weiterer Held mit dem selben Problem.

**Comment by flyx** [comment]
Der Fix behebt das Problem für Helden aus der Mittelreichischen Landbevölkerung. Kann sein, dass es nochmal auftritt für andere Kulturen, falls ja, bitte melden.

Die Muttersprache ist nicht ganz einfach aus dem XML herauszukitzeln, der Import muss dafür wissen, welches die Muttersprache jeder möglichen Kultur ist (außer man kann sie auswählen). Wie die Heldensoftware die Kultur nennt, lässt sich nur durch ausprobieren rausfinden; entsprechend kann es sein, dass noch eine fehlt, die ich bisher nie ausprobiert hab.
