### ISSUE TITLE
Berechnung Geschwindigkeit und Startwerte von Eigenschaften

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#7]
Zwei Fehler bei der Eigenschaften-Tabelle:

1. Bei der Darstellung des Startwertes von Eigenschaften kommt es wohl noch zu einem Fehler. Der Helden Generator zeigt beim angehängten Helden eine GE von 11 an, mit Modifikator dann GE 9. Hier wird zweimal GE 9 angezeigt.
2. Außerdem ist die Geschwindigkeit nicht korrekt. In WdS S 138-139 wird dies erklärt, die Basis ist GS8, aber niedrige GE, gewisse Vor- und Nachteile, sowie BE wirken sich auf die effektive GE aus. Der Helden Generator stellt dies korrekt als Summe aus GS+Modifkatoren+BE unter "Aktuell" dar. Wobei der "Startwert" die "nackte" GS ist, wobei man auch hier streiten kann ob im Beispiel nicht eine 6 stehen sollte, da die GE<10 ist und das im Grunde stets so ist, nicht nur temporär.

![grafik](https://user-images.githubusercontent.com/58633378/172046341-7e728a85-5eee-4d38-8a7a-fcc8175cbb9e.png)
![grafik](https://user-images.githubusercontent.com/58633378/172046500-5ebaf31f-52bd-4068-9fd9-86b93cf704b9.png)

Wie üblich, Held zur Reproduktion: [BernholmvonBellentorKampagne.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8839794/BernholmvonBellentorKampagne.zip)

**Comment by flyx** [comment]
Zu 1.:

Ich würde behaupten, die Heldensoftware hat hier unrecht. Der Grund, warum man den Startwert notiert, ist, damit man weiß, bis wohin man die Eigenschaft steigern darf. Dieses Limit wird *nach* Applikation der Modifikatoren berechnet (WdS S. 165), entsprechend sollte der modifizierte Wert in der **Start**-Spalte stehen, nicht der unmodifizierte Wert wie es die Heldensoftware macht. Wenn du den Wert später steigerst, bleibt der Start-Wert stehen und nur der aktuelle Wert ändert sich, es ist also nicht so, dass versehentlich zweimal derselbe Wert ausgegeben wird, er ist hier nur zufällig gleich.

Zu 2.:

Das war eine bewusste Entscheidung. Ich wollte nicht, dass die Informationen auf dem Front-Bogen von Dingen auf den folgenden Bögen abhängen (deshalb steht zB auch „Gefäß der Sterne“ als Kästchen hier, was es auf dem Original-Bogen nicht gibt). Deshalb steht hier die Grund-GS, ohne irgendwelche Modifikation durch BE.

Ich gebe zu, dass es Sinn ergibt, auch die effektive GS auf dem Bogen zu haben, aber wie du sagst ist es unklar, was gemeint ist, wenn man die beiden Werte in Start und Aktuell reinschreibt. Meine Idee wäre, die effektive GS statt dessen auf den Kampfbogen zu schreiben, da ist noch etwas Platz vertikal. Ich könnte mir zB vorstellen, die Rüstungstabelle zwei Zeilen länger zu machen (ist grad möglicherweise eng, wenn du eine wirklich dicke Dose spielen willst) und dann unter der Silhouette rechts Platz für die effektive GS zu haben.

Was meinst du?

**Comment by pielmach** [comment]
zu 1) Der Verweis auf WdS 165 macht Sinn. Passt.

zu 2) Das Vermeiden der Abhängigkeit auf spätere Seiten ist nachvollziehbar. Was ich aber zumindest erwarten würde, wäre eine Summe aller Modifikatoren auf die GS im Feld Modifikator, also niedrige/hohe GE sowie Vor- und Nachteile, damit man die nackte GS wenigstens kennt. Das ist im Beispielheld zumindest noch nicht der Fall.

Alternativer Layoutvorschlag: Ändere Initiative-Basiswert oben rechts in INI-Basiswert, wie du es ja bei den anderen schon gemacht hast und schau mal ob dann nicht ein GS: X noch in die Zeile passt. Dann hat man die effektive taktische Bewegungsgeschwindigkeit bei den Kampfwerten.

**Comment by flyx** [comment]
Ja also das Problem war dass mein „Fix“ zur Erkennung von *Lahm* nicht vollständig war m(. Das reparier ich gleich, dann steht da der vollständige GS-Modifikator und die daraus resultierende Basis-GS.

> Ändere Initiative-Basiswert oben rechts in INI-Basiswert

Das ist aber ein anderer Wert. „INI-Basiswert“ wird im Regelwerk verwendet für den berechneten Wert aus Eigenschaften und Vor- und Nachteilen (so etwa WdS 52 und LCD 36). „Initiative-Basiswert“ dagegen wird verwendet für den Grundwert, auf den du einen W6 würfelst (also mit Mods aus Kampfreflexe etc, so etwa in WdS S. 74: Kampfgespür erhöht den Initiative-Basiswert; außerdem so definiert auf der Initiative-Übersicht im Anhang des WdS). Manchmal werden aber auch beide Begriffe austauschbar verwendet, etwa WdS 52.

Ich glaube, die sinnvolle Lösung hier ist, den Wert gar nicht da oben hinzuschreiben sondern ganz unten, so wie es das Original-Dokument hat, mit fertiger Formel. Etwa:

> Initiative: [berechneter Wert] + Waffen-INI - BE + 1W6

wobei `[berechneter Wert]` eben INI-Basis + Kampfgespür + Kampfreflexe ist und `1W6` durch `2W6` ersetzt wird, wenn man Klingentänzer hat.

Wenn das unter steht, ist oben Platz für die effektive GS.

**Comment by flyx** [comment]
Habe das mal gemacht, sieht so aus (in diesem Fall mit Klingentänzer):

![initiative](https://flyx.org/files/initiative.png)

Damit ist klar, was alles nicht in dem gegebenen berechneten Wert ist. BE ist nicht reingerechnet um die Formel auch verwenden zu können, wenn man mal keine Rüstung an hat. Waffen-INI muss extra sein weil man ja mitunter verschiedene Waffen hat.

Damit haben wir jetzt:

 * Basis-GS auf der Frontseite, inklusive aller Modifikatoren aus GE, Vor- und Nachteilen
 * Effektive GS auf dem Kampfbogen, Kopfleiste
 * Initiative-Formel mit berechnetem Basis-Wert (wie auch immer der jetzt genannt werden mag) unten auf dem Kampfbogen

Löst das dein Problem?

**Comment by pielmach** [comment]
Klingt gut! :+1:
