### ISSUE TITLE
Feature-Wunsch: Weibliche Silhouette

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#8]
Eine weibliche Silhouette auf dem Kampfbogen, abhängig vom Geschlecht, wäre cool. Würde unsere Spielerinnen freuen.

**Comment by flyx** [comment]
Da bin ich voll bei dir. Leider gehört Zeichnen nicht zum einen Fähigkeiten. Die männliche Silhouette hat mal jemand basierend auf dem Original-Charakterbogen nachgebaut und unter freier Lizenz bereitgestellt, ich müsste kramen wer das war.

Wenn du eine freie Quelle für eine weibliche Silhouette hast oder jemand in deiner Gruppe sich dazu berufen fühlt, kann ich das gerne einbauen. Voraussetzungen wären

 * PNG schwarz mit transparentem Hintergrund
 * Arme / Beine heben sich klar vom Torso ab. sie müssen was die Position angeht nicht auf die männliche Silhouette passen, ich kann die Rüstungs- und Wunden-Marker herumschieben.

**Comment by pielmach** [comment]
Das ist mir bei der Ähnlichkeit erst garnicht aufgefallen. Ist vermutlich die Silhouette aus den https://github.com/thinkingstone/dsa-documents Dokumenten.

Es gibt u.a. Quellen von Silhouetten, die laut der Pixabay Lizenz auch in dem Projekt hier verwendbar sein sollten, z.B. https://pixabay.com/de/vectors/swordswoman-weiblich-frau-m%c3%a4dchen-2756761/ - vielleicht taugt das ja. Ich bin leider kein bischen künstlerisch begabt.

**Comment by flyx** [comment]
Das pixabay-Ding ist nicht schlecht, halt vom Format her zu breit leider. Eignet sich aber wunderbar für eine Google-Bildersuche:

 * https://svgsilh.com/image/1969044.html
 * https://svgsilh.com/image/1676581.html

Letzteres erscheint mir besser geeignet weil neutraler, allerdings ist die angedeutete Kleidung jetzt eher nicht outdoor-tauglich.

Wo ich grad darüber nachdenk, eine meiner Spielerinnen kann zeichnen, ich frag sie mal ob sie da Lust hat was zu machen.

**Comment by flyx** [comment]
… sie hatte Lust :)
