### ISSUE TITLE
Personalisierte Waffen und Rüstungen

### ISSUE THREAD

**Issue by pielmach** [flyx/DSA-4.1-Heldendokument#9]
Personalisierte, d.h. verbesserte Waffen, oder auch z.B. hervorragende Kettenrüstungen, die einen weiteren Stern haben, werden nicht korrekt erkannt. Die Daten dazu stehen grundsätzlich im helden XML mit drin. Anbei ein Held der ein verbessertes Kurzschwert hat und eine hervorragende Kettenweste, beides wird aktuell durch ein entsprechendes 0815 Gegenstück ersetzt.

[WulfjewFirunkis.zip](https://github.com/flyx/DSA-4.1-Heldendokument/files/8839807/WulfjewFirunkis.zip)

**Comment by flyx** [comment]
Okay ich *glaube* ich habe verstanden was die Heldensoftware produziert. Ich arbeite daran im branch `gegenstaende`, das wird ein paar Tests brauchen um sicherzustellen dass auch der Import von Standardwaffen nicht kaputt geht.

**Comment by flyx** [comment]
Die größte Hürde hier sind die verbesserten Rüstungsteile. Die Heldensoftware gibt da eine Anzahl Sterne an, mit der der Heldenbogen absolut nichts anfangen kann. Ich müsste den Heldenbogen an der Stelle umschreiben, damit er den Unterschied zwischen Rüstungsteilen und Komplett-/Torsorüstungen kennt und der gRS berechnet wird statt dass er Teil der Eingabe ist.

Ich stelle das hier mal hinten an, weil es viel Arbeit ist, die nachträgliche Korrektur in der Lua-Datei dagegen relativ einfach.

**Comment by pielmach** [comment]
Macht Sinn. Nicht alles muss implementiert werden. Ich würde empfehlen dann bei solchen "Known Limitations" diese evt. konkret auf der Website aufzulisten. Idealerweise mit kurzem Kommentar wie man es "richtig" behebt. Mit Docker, Latex und Lua, und ohne Formularfelder im PDF ist die Einstiegsschwelle deines Generators schon ziemlich hoch :wink: 

Auch die optionalen Mirkal+ Talente muss man ja von Hand nachtragen im Lua File.

**Comment by flyx** [comment]
> Mit Docker, Latex und Lua, und ohne Formularfelder im PDF ist die Einstiegsschwelle deines Generators schon ziemlich hoch

Ja, ich würde auch lieber das fertige Webinterface anbieten, aber geht halt leider nicht wegen der Urheberrechtsgeschichte. Prinzipiell könnte man ein Plugin für die Heldensoftware schreiben, das voraussetzt, dass im Hintergrund Docker läuft, und das dann automatisch das Docker-Image baut und dann den Import & das Rendering durch Benutzerinteraktion anstoßen kann – das Webinterface ist RESTful, für den Fortschrittsbalken braucht man Websockets, ist alles keine Raketenwissenschaft. Müsste man halt machen, und ich sehe mich da jetzt eher nicht Zeit reininvestieren.

> Auch die optionalen Mirkal+ Talente muss man ja von Hand nachtragen im Lua File.

Da frage ich mich, ob es eine bessere Lösung gibt. Die Heldensoftware weiß nichts von Mirakel+/-, also könnte man es allenfalls in die Notizen schreiben in irgendeinem definierten Format, das der Import auslesen kann. Oder halt wieder ein Plugin schreiben, um diese Information hinzuzufügen. Letzteres sehe ich nicht passieren, aber ersteres ginge, zB in der Art:

> Mirakel+: Talent1, Talent2  
> Mirakel-: Talent3, Talent4

Wenn das so in den Notizen steht, *könnte* man es im Import automatisch verarbeiten.

**Comment by flyx** [comment]
So, prinzipiell sollte das jetzt alles tun. Ich komme die nächsten Tage vmtl erstmal nicht dazu, das ausgiebig zu testen, deshalb bleibt das erstmal im `gegenstaende` branch – falls du Lust dazu hast, nur zu :)

Änderungen im Einzelnen:

 * Nahkampfwaffen: Import von Modifikationen
 * Fernkampfwaffen: Import von Modifikationen; Laden-Spalte (kann ja auch modifiziert werden), Anzeige von verminderter Wundschwelle
 * Schilde/Parierwaffen: Import von Modifikationen
 * Rüstung: gBE und gRS werden nicht mehr angegeben sondern automatisch berechnet auf basis von Z und Sternen; Import von Modifikationen

**Comment by flyx** [comment]
Die Anpassungen sind jetzt in `master`. Ich habe ein wenig getestet und keine Probleme gefunden.

 Für besseren Transport von der Heldensoftware unbekannten Daten gibts jetzt #15.

**Comment by pielmach** [comment]
Bin eben erst zum Testen gekommen und sieht soweit alles sehr gut aus. Zwei "Details" sind mir noch aufgefallen, kannst du bei mit dem Helden Wulfjew aus dem Eingangspost nachvollziehen:

1) Die Talentspezialisierung scheint bei den Fernkampfwaffen nicht berücksichtigt zu werden.
2) Die Namen der angepassten Waffen scheinen nicht immer portiert zu werden. Sowohl bei beiden Fernkampfwaffen als auch beim Kurzschwert wurde der Name editiert.

**Comment by flyx** [comment]
5df212f2d8c75ff0bcb1ecd80c85b6cefc7af6c2 adressiert diese Probleme. Wenn ich nichts übersehen habe, werden die geänderten Namen jetzt korrekt importiert und die Talentspezialisierung korrekt eingerechnet.
